package constants

const (
	FuncGetAccounts                = "GetAccounts"
	FuncGetOrderChance             = "GetOrderChance"
	FuncGetOrder                   = "GetOrder"
	FuncGetOrders                  = "GetOrders"
	FuncPurchaseOrder              = "PurchaseOrder"
	FuncSellOrder                  = "SellOrder"
	FuncCancelOrder                = "CancelOrder"
	FuncGetWithdraws               = "GetWithdraws"
	FuncGetWithdraw                = "GetWithdraw"
	FuncGetWithdrawChance          = "GetWithdrawChance"
	FuncWithdrawCoin               = "WithdrawCoin"
	FuncWithdrawKrw                = "WithdrawKrw"
	FuncGetDeposits                = "GetDeposits"
	FuncGetDeposit                 = "GetDeposit"
	FuncGenerateDepositCoinAddress = "GenerateDepositCoinAddress"
	FuncGetDepositCoinAddresses    = "GetDepositCoinAddresses"
	FuncGetDepositCoinAddress      = "GetDepositCoinAddress"
	FuncDepositKrw                 = "DepositKrw"
	FuncGetWalletStatus            = "GetWalletStatus"
	FuncGetApiKeys                 = "GetApiKeys"
	FuncGetMarkets                 = "GetMarkets"
	FuncGetMinuteCandles           = "GetMinuteCandles"
	FuncGetDayCandles              = "GetDayCandles"
	FuncGetWeekCandles             = "GetWeekCandles"
	FuncGetMonthCandles            = "GetMonthCandles"
	FuncGetTradeTicks              = "GetTradeTicks"
	FuncGetTickers                 = "GetTickers"
	FuncGetOrderbooks              = "GetOrderbooks"

	RouteAccounts                    = "/accounts"
	RouteOrderChance                 = "/orders/chance"
	RouteOrder                       = "/order"
	RouteOrders                      = "/orders"
	RouteWithdraws                   = "/withdraws"
	RouteWithdraw                    = "/withdraw"
	RouteWithdrawsChance             = "/withdraws/chance"
	RouteWithdrawsCoin               = "/withdraws/coin"
	RouteWithdrawsKrw                = "/withdraws/krw"
	RouteDeposits                    = "/deposits"
	RouteDeposit                     = "/deposit"
	RouteDepositsGenerateCoinAddress = "/deposits/generate_coin_address"
	RouteDepositsCoinAddresses       = "/deposits/coin_addresses"
	RouteDepositsCoinAddress         = "/deposits/coin_address"
	RouteDepositsKrw                 = "/deposits/krw"
	RouteStatusWallet                = "/status/wallet"
	RouteApiKeys                     = "/api_keys"
	RouteMarketAll                   = "/market/all"
	RouteCandlesMinutes              = "/candles/minutes/"
	RouteCandlesDays                 = "/candles/days"
	RouteCandlesWeeks                = "/candles/weeks"
	RouteCandlesMonths               = "/candles/months"
	RouteTradesTicks                 = "/trades/ticks"
	RouteTicker                      = "/ticker"
	RouteOrderbook                   = "/orderbook"

	ApiSectionExchange  = "exchange"
	ApiSectionQuotation = "quotation"

	ApiGroupDefault      = "default"
	ApiGroupOrder        = "order"
	ApiGroupStatusWallet = "status-wallet"
	ApiGroupMarket       = "market"
	ApiGroupCandles      = "candles"
	ApiGroupCrixTrades   = "crix-trades"
	ApiGroupTicker       = "ticker"
	ApiGroupOrderbook    = "orderbook"
)
