definitions:
  auth.ReqRegister:
    properties:
      upbit_access_key:
        type: string
      upbit_secret_key:
        type: string
    required:
    - upbit_access_key
    - upbit_secret_key
    type: object
  auth.RespRegister:
    properties:
      message:
        type: string
      status_code:
        type: integer
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: 회원가입
      parameters:
      - description: 접근 키, 시크릿 키
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.ReqRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.RespRegister'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/auth.RespRegister'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/auth.RespRegister'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/auth.RespRegister'
      summary: 회원가입
      tags:
      - auth
swagger: "2.0"
